### ISSUE TITLE
Can we disbale Style/SymbolArray Style/WordArray 

### ISSUE THREAD

**Issue by ljones140** [simplybusiness/simplycop#16]
# Why
%i[foo, bar] is not better than: [:foo, :bar]

%w[foo, bar] is not better than: ['foo', 'bar']
If a word with a space is added the whole array needs to be changes

**Comment by sebastian-nanek** [comment]
I agree with the above. Can you raise a PR?

**Comment by budmc29** [comment]
We can, and we did.

**Comment by ljones140** [comment]
Linke to PR that resolved issue: https://github.com/simplybusiness/simplycop/pull/17
